### ISSUE TITLE
Rotas não podem ser acessadas diretamente

### ISSUE THREAD

**Issue by joaomarcosdesouza** [d3estudio/zag-app-web#13]

**Comment by joaomarcosdesouza** [comment]
![img_1484](https://cloud.githubusercontent.com/assets/1846975/18205527/da0f525e-70f8-11e6-8fba-339c91942594.png)

**Comment by mathportillo** [comment]
resolvido em eadffa9c525fdef2a427381f7e0ffa6e4b60b78b
