### ISSUE TITLE
Máscara do campo de valor (ex.: 0,00) permite seleção livre

### ISSUE THREAD

**Issue by joaomarcosdesouza** [d3estudio/zag-app-web#23]
Sugestões:
- Quando seleciona o campo limpa a máscara de "0,00" para ""
- Ou coloca o cursor sempre no início da máscara

**Comment by mathportillo** [comment]
Atualmente coloca o cursor no final da string quando o user dá `onfocus`. Se a pessoa tocar denovo em outra posição o cursor reposiciona. Isso que descrevi não é o ideal? ou não está funcionando? @joaomarcosdesouza

**Comment by KalebPortillo** [comment]
eu implementei que no onclick sempre vai pra ultima posicao, ai vai ser impossivel a pessoa editar o valor se nao for pelo ultimo caractere, blz? @joaomarcosdesouza

**Comment by joaomarcosdesouza** [comment]
Blz @KalebPortillo

**Comment by joaomarcosdesouza** [comment]
@KalebPortillo: no desktop funciona, mas no iOS ainda não está funcionando
