### ISSUE TITLE
Descrever mensagens de erro da forma mais clara possível ao usuário. (sem código de erro)

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-app-web#29]
Na área de login, informar qual o erro exato que aconteceu:
Falha no servidor, E-mail não cadastrado, Senha inválida, etc

![img_7903 1](https://cloud.githubusercontent.com/assets/20709505/18215558/211d0270-7128-11e6-966c-974afaf2f0d3.PNG)

**Comment by KalebPortillo** [comment]
#32 Duplicate
