### ISSUE TITLE
Alterar todos os textos de erro / alertas para português.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/zag-app-web#32]

**Comment by KalebPortillo** [comment]
preciso de todos os erros possiveis que vem do server @mathportillo

**Comment by mathportillo** [comment]
Citando wiki da `api`
Errors are expected to be sent using the following data structure:

`error`: Unhumanised error code, useful for checking error reason, and perhaps checking error source through a `switch` mechanism or such.
`message`: Humanised error message. Useful if showing the error message to a final user.
`action`: Recommended action for recovering from error.


Fiz uma lista de erros possíveis que pude encontrar até agora (cc @victorgama pode colocar isso pra iniciar algo no wiki também):
```ruby
#REFUNDS CONTROLLER
error: 'MissingTag',
message: 'You must provide an internal tag for the refund',
action: 'Retry'

error: 'ClientInconsistency',
message: 'Unable to store a mileage-based refund without proper company configuration',
action: 'Report'

error: 'InternalError',
message: 'Refund could not be saved',
action: 'Report'

error: 'ValidationError',
action: 'Retry'



#AUTHENTICATION TRAITS
error: 'MissingAuthenticationData',
message: 'You must provide both an app_id and a signature for OAuth authentication. Missing signature.',
action: 'Retry'

error: 'MissingAuthenticationData',
message: 'You must provide both an app_id and a signature for OAuth authentication. Missing app_id.',
action: 'Retry'

error: 'InvalidApp',
message: 'Provided app_id does not belong to a known app',
action: 'Retry'

error: 'InvalidSignature',
message: 'Provided signature does not match the server expectations',
action: 'Retry'

error: 'MissingAuthenticationData',
message: 'You must provide a token for this endpoint.',
action: 'Retry'

error: 'InvalidToken',
message: 'Provided token is either expired or does not exist',
action: 'Reauthenticate'

error: 'MissingAuthenticationData',
message: 'You must provide a signature for POST requests. For further information, refer to the documentation.',
action: 'Retry'

error: 'InvalidSignature',
message: 'Provided signature does not match the server expectations',
action: 'Retry'

error: 'InsufficientPermission',
message: 'You do not have permission to access the requested resource.',
action: 'Stop'



#O_AUTH CONTROLLER
error: 'InvalidCredentials',
message: 'The email/password combination does not match any user',
action: 'Retry'

error: 'AccountNotConfirmed',
message: 'This account has not been confirmed yet',
action: 'ConfirmAccount'

error: 'InvalidApplication',
message: 'The provided app_id does not belong to a known application',
action: 'Stop'

error: 'InvalidSignature',
message: 'The provided signature does not match the server expectation',
action: 'Retry'

error: 'Forbidden',
message: 'Your application does not have privilege to access the requested resource',
action: 'Stop'


#USERS_CONTROLLER
error: 'ValidationError',
message: 'Missing term field',
action: 'Retry'

#REFUNDS CONTROLLER
error: 'ValidationError',
message: 'Missing status field',
action: 'Retry' 

error: 'ValidationError',
message: "Invalid status value. Valid values are " [[LIST]],
action: 'Retry'

error: 'ValidationError',
message: "A reason field is required to change the status to the provided one",
action: 'Retry'

error: 'ValidationError',
message: 'Missing ids field',
action: 'Retry'

error: 'ValidationError',
message: 'Only approved refunds can be set as paid.',
action: 'Retry'

```

**Comment by victorgama** [comment]
@mathportillo Perfeito! Essa tarefa está meio pendente, hehe. Tem um link quebrado no começo da documentação de endpoints da API. Em breve atualizarei com essa lista. <3

**Comment by victorgama** [comment]
@KalebPortillo Posso incluir um novo campo com um identificador único pra cada erro, ou tentar colocar essas mensagens num dicionário, e o Rails se vira com o i18n. O problema da segunda opção, é que o Rails não terá informação suficiente de localização, dado que as requests passam pelos proxies/wrappers.

**Comment by KalebPortillo** [comment]
Por enquanto vamos deixar uma mensagem pra cada tipo de erro, mas nao sei se o @juniormag quer que depois tenhamos umas mensagens mais localizadas.

**Comment by victorgama** [comment]
Se formos usar um identificador único pra cada erro, a hora é agora. :shipit:

**Comment by juniormag** [comment]
#REFUNDS CONTROLLER
error: 'MissingTag',
message: 'You must provide an internal tag for the refund',

`Algo estranho aconteceu. Tente novamente - Erro(301)`

error: 'ClientInconsistency',
message: 'Unable to store a mileage-based refund without proper company configuration',

`Algo estranho aconteceu. Tente novamente - Erro(302)`  

error: 'InternalError',
message: 'Refund could not be saved',

`O zag não conseguiu salvar seu reembolso :/ Tente novamente - Erro(303)`

error: 'ValidationError',

`Problema na validação. Tente novamente - Erro(304)`


#AUTHENTICATION TRAITS
error: 'MissingAuthenticationData',
message: 'You must provide both an app_id and a signature for OAuth authentication. Missing signature.',

`Algo estranho aconteceu. Tente novamente - Erro(305)`

error: 'MissingAuthenticationData',
message: 'You must provide both an app_id and a signature for OAuth authentication. Missing app_id.',

`Algo estranho aconteceu. Tente novamente - Erro(306)`

error: 'InvalidApp',
message: 'Provided app_id does not belong to a known app',

`Algo estranho aconteceu. Tente novamente - Erro(307)`

error: 'InvalidSignature',
message: 'Provided signature does not match the server expectations',

`Algo estranho aconteceu. Tente novamente - Erro(308)`

error: 'MissingAuthenticationData',
message: 'You must provide a token for this endpoint.',

`Algo estranho aconteceu. Tente novamente -  Erro(309)`

error: 'InvalidToken',
message: 'Provided token is either expired or does not exist',

`Algo estranho aconteceu. Tente novamente - Erro(310)`

error: 'MissingAuthenticationData',
message: 'You must provide a signature for POST requests. For further information, refer to the documentation.',

`Algo estranho aconteceu. Tente novamente - Erro(311)`

error: 'InvalidSignature',
message: 'Provided signature does not match the server expectations',

`Algo estranho aconteceu. Tente novamente - Erro(312)`

error: 'InsufficientPermission',
message: 'You do not have permission to access the requested resource.',

`Algo estranho aconteceu. Tente novamente - Erro(313)`



#O_AUTH CONTROLLER
error: 'InvalidCredentials',
message: 'The email/password combination does not match any user',

`Opa! Seu login e/ou senha estão incorretos. Esqueceu?`

error: 'AccountNotConfirmed',
message: 'This account has not been confirmed yet',

`Eita! Parece que sua conta não foi confirmada ainda.`

error: 'InvalidApplication',
message: 'The provided app_id does not belong to a known application',

`Algo estranho aconteceu. Tente novamente - Erro(314)`


error: 'InvalidSignature',
message: 'The provided signature does not match the server expectation',

`Algo estranho aconteceu. Tente novamente - Erro(315)`

error: 'Forbidden',
message: 'Your application does not have privilege to access the requested resource',

`Algo estranho aconteceu. Tente novamente - Erro(316)`


#USERS_CONTROLLER
error: 'ValidationError',
message: 'Missing term field',

`Algo estranho aconteceu. Tente novamente - Erro(317)`

#REFUNDS CONTROLLER
error: 'ValidationError',
message: 'Missing status field', 

`Algo estranho aconteceu. Tente novamente - Erro(318)`

**Comment by victorgama** [comment]
@KalebPortillo d3estudio/zag-api#f2b826f implementa os descritores que você estava precisando. Pré-compilei uma lista com todos os identificadores possíveis [na wiki do repositório](https://github.com/d3estudio/zag-api/wiki/Error-Identifiers). Por hora, ficarei devendo os de validação de campos (porque precisarei iterar um array que o Rails me entrega), mas logo menos estará pronto.
