### ISSUE TITLE
Quando cadastro Km no reembolso e depois edito para R$ ele atualiza o valor, mas mantém o km no label abaixo do preço

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-app-web#34]

**Comment by victorgama** [comment]
Causado por uma inconsistência no handling de refunds baseados em quilometragem. Pode ser iterado depois que d3estudio/zag-api#11 for resolvido.

**Comment by victorgama** [comment]
Comportamento corrigido em [387b31e](https://github.com/d3estudio/zag-api/commit/387b31e99308f8d78216e611ce743becdd082149).

@lucasartacho Você pode confirmar junto com o @mathportillo? :)

**Comment by mathportillo** [comment]
Confirmado!

**Comment by victorgama** [comment]
🐞 + ✋ + 💨 
〰️ 〰️ 〰️ 〰️ 
= 💀  🙌 

💀🐞
