### ISSUE TITLE
Reverter nome do campo de attachment

### ISSUE THREAD

**Issue by victorgama** [d3estudio/zag-app-web#39]
É seguro utilizar `attachment` ao invés de `attachment-b64`, se considerarmos que todos os requests que utilizarem base64 terão um prefixo informando o tipo de dado encodado: `data:image/png;base64,<base64-encoded-value>`.

É importante ressaltar que, nesse caso, o conteúdo do campo deverá ser considerado enquanto calculando a assinatura OAuth do request. O mesmo não deverá ser feito quando enviando um arquivo em multipart.

**Comment by mathportillo** [comment]
fixed by 8479cb9e1a912108c8693d1db90a6bc83d5581ab

**Comment by victorgama** [comment]
Thanks! 💖
