### ISSUE TITLE
O cadastro de reembolso por Km não conclui, está retornando erro.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-app-web#40]
"Erro desconhecido tente novamente"
![img-20160904-wa0001](https://cloud.githubusercontent.com/assets/20709505/18251235/5f6a6814-735e-11e6-82c0-720be343695d.jpg)

**Comment by juniormag** [comment]
Precisamos dar uma revisada no tamanho dessa fonte também conforme o layout

**Comment by juniormag** [comment]
Não conseguimos cadastrar reembolsos em KM caso a empresa não tenha cadastrado o valor em R$ por KM. Nesse caso, a função de kilometragem ficará disabled.

**Comment by mathportillo** [comment]
fixed by f0a8f8e73598d839bfc3f2ebb5afc2647a6ec382
