### ISSUE TITLE
Windows Phone: O 'blinking text cursor' não aparece nos campos de texto usuário e senha.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-app-web#41]
![img-20160904-wa0003](https://cloud.githubusercontent.com/assets/20709505/18251359/23fd67c6-735f-11e6-9934-034580a0aeca.jpg)

**Comment by juniormag** [comment]
Lucas, tem chance que isso seja decorrente do sistema e não da aplicação
