### ISSUE TITLE
iOS / Safari / Android/ Chrome: Btn finalizar fica por cima do conteúdo quando o teclado está ativo.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-app-web#5]
![img_7895](https://cloud.githubusercontent.com/assets/20709505/18187946/2d97469a-7084-11e6-82da-b85f976a9904.PNG)
![screenshot_2016-09-01-20-25-00](https://cloud.githubusercontent.com/assets/20709505/18187945/2d94c2ee-7084-11e6-9ba2-9ba1a021ebc4.png)

**Comment by phillfer** [comment]
adiciona 'position: relative' no botao 'refund-button-container' enquanto tiver focus nos campos de input. quando sair do focus volta pra 'position:fixed'
