### ISSUE TITLE
iOS / Safari: Deletar imagem não funciona

### ISSUE THREAD

**Issue by joaomarcosdesouza** [d3estudio/zag-app-web#54]

**Comment by KalebPortillo** [comment]
Nao funciona no front pu quando vc salva o refund sem imagem a imagem na e deletada no server?

**Comment by juniormag** [comment]
@KalebPortillo O caso de uso é: Usuário edita um reembolso com imagem, exclui ela na edição, o app não retorna nenhum erro e quando ele vai ao detalhamento do histórico novamente o reembolso aparece da mesma forma com a mesma imagem.
