### ISSUE TITLE
Android / Chrome: Ícone de adicionar photo aparece cortado.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/zag-app-web#61]
O ícone de adicionar photo aparece cortado quando o reembolso está em KM.
![screenshot_2016-09-14-11-14-43](https://cloud.githubusercontent.com/assets/20709505/18516093/0e4617b4-7a6e-11e6-8537-e748c0b11608.png)

**Comment by KalebPortillo** [comment]
Noa consegui reproduzir
